### ISSUE TITLE
Create "InfoCards" of extractable stories

### ISSUE THREAD

**Issue by bnvk** [TransparencyToolkit/LookingGlass#11]
The site [http://infogra.ph](http://infogra.ph) creates some pretty interesting little infographic cards that tell a story. It would be interesting if we could tease out information like this into widgets

![screen shot 2015-04-21 at 10 20 48 am](https://cloud.githubusercontent.com/assets/48677/7248250/a5983bba-e811-11e4-8746-1423e4720e3c.png)

**Comment by Shidash** [comment]
Going to close this for now (for reasons explained in other issues), but maybe eventually we should allow people to add visualizations and infographics on the public instances. Or even a page with a description of the data that people view the archive for that matter. In general we should have better support for data about the data and ways to display that on the published instances.
