### ISSUE TITLE
Overview data visualization browsable by indexes

### ISSUE THREAD

**Issue by bnvk** [TransparencyToolkit/LookingGlass#12]
This data visualization about [People Killed by Police in America](http://1point21interactive.com/people-killed/) does some interesting composite overviews of all the data that is then filterable by Year, Weapon, Etc...

![screen shot 2015-04-21 at 10 35 15 am](https://cloud.githubusercontent.com/assets/48677/7248358/67932edc-e812-11e4-932c-12dcaaa817b3.png)

![screen shot 2015-04-21 at 10 37 00 am](https://cloud.githubusercontent.com/assets/48677/7248360/67be7e02-e812-11e4-8446-3f58e52369c3.png)

**Comment by Shidash** [comment]
Going to close this for now (about to add a bunch of issues on things we need to clean up on software during feature freeze), but adding visualizations of facets is definitely something we should do at some point and we should look through examples like this then.
