### ISSUE TITLE
Implement the idea of "Anomalies" 

### ISSUE THREAD

**Issue by bnvk** [TransparencyToolkit/LookingGlass#18]
Basically a way for a human to "tag" one point of data in a given search result item as something of interest or an "anomaly" such as:
- Job at Defense Contractor
- Job at Pharmacy
- Job at Defense Contractor
- Job in Military
- Job at Defense Contractor

The thinking here being that once a user (of LookingGlass) flags something as an anomaly, they can then view other anomalies with the goal of perhaps finding patterns between anomalies. In the above case there might be "another person who worked at a similarly odd company in between defense contracting gigs during the same few year period"

**Comment by Shidash** [comment]
This can be done with editable fields (already added) and will be even more feasible once we give users the ability to add custom fields. So closing this for now.

This is something we probably want to come back to in more depth though as eventually I'd like to have the user-tagged documents and similar serve as a training set for machine learning algorithms people could use via Catalyst (or also offer this sort of anomaly detection without user input).
