### ISSUE TITLE
Cloudflare settings for Tor visitors

### ISSUE THREAD

**Issue by glamrock** [TransparencyToolkit/LookingGlass#22]
So everything is fine when viewing the ICWATCH site directly, but when visiting via Tor there's a nonspecific error that may be related to the CloudFlare settings.  Here's a screenshot:

![screenshot from 2015-05-08 14 08 45](https://cloud.githubusercontent.com/assets/452041/7542612/3438ba5c-f58c-11e4-8beb-6412a630fef7.png)

**Comment by glamrock** [comment]
Okay, this problem seems to be more intermittent as now it seems to be gone. Hmm.

**Comment by Shidash** [comment]
Tor exits are whitelisted now.
