### ISSUE TITLE
Need dynamic element IDs for diffing

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/LookingGlass#40]
I made the diffing code work with the data loaded into LookingGlass. However, the ids for the diffing elements (like versions-container) are constant and hardcoded into the Javascript.

This is a problem because, due to the structure of the data where multiple items show per page, sometimes there need to be multiple diffing containers per page. This doesn't work with constant IDs. Is there a way to make them dynamic?

It seems like there are a couple ways this could be approached-
1. The html for diffing is now in app/views/docs/_changetracker.html.erb. Setting dynamic ids based on the doc ID would be quite easy here. But these need to be matched up in the JS somehow. Perhaps they could have a common class and the current JS could be run for each element in the class, but without the ID hardcoded?
2. The html for versions-diffing-type, versions-compute, and versions-diff could be rendered only once on the page and the div with the id versions-container could have a class of versions-container instead. Then all elements with this class could be added to the list to be diffed. These elements may require unique IDs themselves that correlate them to the appropriate doc (rather than just using the field name as the ID like they currently do).

The first solution seems preferable visually to me, but of course there may be other options too. What do you think?

To duplicate this issue, you should-
1. Download the new test data on the server from /mnt/disk/processed_test_data
2. Clone and use the current dataspec-linkedin repo
3. Change the path in the dataset_details in the dataspec-linkedin folder to point to the location of processed_test_data
4. Index the data with rails runner as normal
5. Open the search and look for Aziz Omar

**Comment by bnvk** [comment]
Closing this as it's now debugging and being tracked in #42
