### ISSUE TITLE
Search result formatting where there is long text but not description

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/LookingGlass#45]
In datasets where there is a field of display type Long Text but not of display type Description, the Long Text field shows up to the right and there is a large blank space on the left. When there is no Description type field, this should be single column.

This should work to check if there are description fields/get the num of description fields-
dataspec.field_info.select{|f| f["Display Type"]== "Description"}.length
You may need to use @dataspec or a different var depending on what dataspec is where this is called.

**Comment by bnvk** [comment]
This is now fixed!
