### ISSUE TITLE
Move "dataset_details.json" to instance config.json

### ISSUE THREAD

**Issue by bnvk** [TransparencyToolkit/LookingGlass#48]
Currently the dataspec file for a given type of data collection source- e.g. for LinkedIn is in: `app/dataspec/dataspec-linkedin/dataset_details.json`

This file contains values like `"Path": "/home/username/Data/processed_version_error"` and since this info changes from instance to instance- this should probably be moved to the `instance-config.json` file!

**Comment by Shidash** [comment]
Path is no longer in the dataspec
