### ISSUE TITLE
Empty query value returns nasty error page

### ISSUE THREAD

**Issue by bnvk** [TransparencyToolkit/LookingGlass#49]
Go to a URL like this [http://localhost:3000/search?utf8=%E2%9C%93&utf8=%E2%9C%93&q=](http://localhost:3000/search?utf8=%E2%9C%93&utf8=%E2%9C%93&q=) when an empty query string and you will notice a nasty error page.

We should handle this a bit better and just redirect to the homepage or such!

**Comment by Shidash** [comment]
Fixed during ICWatch update in late January/early February
