### ISSUE TITLE
Compatibility with ElasticSearch 2.x

### ISSUE THREAD

**Issue by ageis** [TransparencyToolkit/LookingGlass#54]
It appears we are currently pegged to ElasticSearch 1.5.2. I tested LookingGlass on 2.3.x, 1.6.x and 1.7.x with errors and negative results.

The reason the application is incompatible is because it relies heavily on [Facets](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-facets.html), which were already deprecated in the version that is being used. In ElasticSearch 2.x, they have been replaced with [Aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-aggregations.html). They have some useful docs on [how to migrate](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-facets-migrating-to-aggs.html) from Facets to Aggregations.

Since there is lots of code that is affected here, it is quite a task to migrate to the latest ElasticSearch. But hopefully we can get it done eventually.

**Comment by Shidash** [comment]
Latest version upgrades to elasticsearch 5.2.2
