### ISSUE TITLE
Dataspecs are referenced in the installation but not present

### ISSUE THREAD

**Issue by andrewjwolf** [TransparencyToolkit/LookingGlass#59]
Currently you need to manually copy the dataspec-IndeedCrawl and dataspec-LinkdinCrawl to thhe app/dataspec folder.

This isn't mentioned in the readme.md

**Comment by Shidash** [comment]
The software has been significantly restructured since this issue was open and now dataspecs are managed by DocManager: https://github.com/TransparencyToolkit/DocManager
There are some default ones that are included by default, but the new hosted archiving service manages dataspecs automatically.
