### ISSUE TITLE
Dropdown with different options for adding data

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/LookingGlass#68]
Reorganize the topbar on editable LG to have a dropdown with the different ways of adding content (currently a link to the upload form and a link to the entity form). Also try to make the wording clearer.

**Comment by bnvk** [comment]
Implemented along with #69 see screenshot

![tt-lg-settings-menu](https://user-images.githubusercontent.com/48677/68679381-0bba9d00-0560-11ea-9120-cda8c973d8f3.png)
