### ISSUE TITLE
Add edit settings link to LG

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/LookingGlass#69]
The archive settings are managed by the ArchiveAdmin app, but there should be a link to edit them from LG.

**Comment by bnvk** [comment]
I've gone through a few iterations of how this is best placed. Here is what i've settled on to make best use of available navbar space and match what Admin interface shows.

![tt-lg-settings-menu](https://user-images.githubusercontent.com/48677/68679146-98b12680-055f-11ea-88df-0821088311e2.png)

Closing this as pretty much implemented.
