### ISSUE TITLE
Add DateTime Search/Display

### ISSUE THREAD

**Issue by Shidash** [TransparencyToolkit/LookingGlass#86]
Add search and display for DateTime parameters

**Comment by Shidash** [comment]
What's the status of the date/time picker? Think we need one like there is for dates fully working to get datetime queries to work.

**Comment by bnvk** [comment]
Finished this in a0c72f65b7437538b49f7b5dcd9c7b7b8abfd23b as discussed elsewhere may be migrating this to just `date` in future.
